# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSanEH9gLiaeLIlRKI4kqpjeXn8FVC_7

# ============================================
# Chidimma Ukoha — Text Analyst
# Multimodal Crime / Incident Report Analyzer
# Tools: spaCy, HuggingFace Transformers, NLTK
# Dataset: CrimeReport Twitter Dataset
# ============================================
"""

!pip install spacy transformers nltk pandas -q
!python -m spacy download en_core_web_sm

import pandas as pd
import spacy
import nltk
import re

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

nlp = spacy.load("en_core_web_sm")

print("✅ All libraries loaded successfully!")

import os

# Create kaggle directory
os.makedirs('/root/.kaggle', exist_ok=True)

# Write credentials using your token
kaggle_token = "KGAT_fa6598a3dba25298f495360626276b82"  # your token

# Get your Kaggle username from kaggle.com/settings
kaggle_username = "chidimmaukoha"  # replace this

# Create kaggle.json
import json
creds = {"username": kaggle_username, "key": kaggle_token}

with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump(creds, f)

os.chmod('/root/.kaggle/kaggle.json', 0o600)
print("✅ Kaggle credentials saved!")

!kaggle datasets download -d cameliasiadat/crimereport --unzip
print("✅ Dataset downloaded!")

import json

records = []
with open('/content/CrimeReport (1).txt', 'r') as f:
    for line in f:
        line = line.strip()
        if line:
            try:
                record = json.loads(line)
                records.append(record)
            except:
                pass

df_raw = pd.DataFrame(records)
print("✅ Raw data reloaded! Tweets:", len(df_raw))

import os

# Check current directory
print("Files in current directory:")
print(os.listdir('/content'))

# Read first 5 lines to see what format it is
with open('/content/CrimeReport (1).txt', 'r') as f:
    for i, line in enumerate(f):
        print(line)
        if i == 4:
            break

import json
import pandas as pd

records = []

with open('/content/CrimeReport (1).txt', 'r') as f:
    for line in f:
        line = line.strip()
        if line:
            try:
                record = json.loads(line)
                records.append(record)
            except:
                pass

df_raw = pd.DataFrame(records)

print("Total tweets loaded:", len(df_raw))
print("\nColumns:", df_raw.columns.tolist())
df_raw.head(3)

# Extract only the useful columns for our analysis
df = pd.DataFrame()

df['Raw_Text'] = df_raw['text']
df['Created_At'] = df_raw['created_at']

# Extract place/location safely (some tweets may not have place info)
df['Location'] = df_raw['place'].apply(
    lambda x: x['full_name'] if isinstance(x, dict) else 'Unknown'
)

# Extract username safely
df['Username'] = df_raw['user'].apply(
    lambda x: x['screen_name'] if isinstance(x, dict) else 'Unknown'
)

# Add source column
df['Source'] = 'Twitter'

# Add Text_ID
df['Text_ID'] = ['TXT_' + str(i).zfill(3) for i in range(1, len(df)+1)]

# Reorder columns
df = df[['Text_ID', 'Source', 'Username', 'Created_At', 'Location', 'Raw_Text']]

# Save to CSV
df.to_csv('/content/crimereport.csv', index=False)

print("✅ Saved as crimereport.csv!")
print("Shape:", df.shape)
df.head(3)

import re

def clean_text(text):
    text = str(text)
    text = re.sub(r'http\S+', '', text)         # remove URLs
    text = re.sub(r'@\w+', '', text)            # remove @mentions
    text = re.sub(r'#\w+', '', text)            # remove hashtags
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text) # remove special chars
    text = re.sub(r'\s+', ' ', text).strip()   # normalize whitespace
    return text

df['Clean_Text'] = df['Raw_Text'].apply(clean_text)

print("✅ Text cleaned!")
print("\nOriginal:", df['Raw_Text'][0])
print("\nCleaned: ", df['Clean_Text'][0])

import spacy
nlp = spacy.load("en_core_web_sm")

def extract_entities(text):
    doc = nlp(str(text))
    relevant = [
        ent.text for ent in doc.ents
        if ent.label_ in ['GPE', 'LOC', 'PERSON', 'ORG', 'DATE']
    ]
    return ', '.join(relevant) if relevant else 'None'

df['Entities'] = df['Clean_Text'].apply(extract_entities)

print("✅ Entities extracted!")
df[['Text_ID', 'Clean_Text', 'Entities']].head(5)

from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis")

def get_sentiment(text):
    try:
        result = sentiment_pipeline(str(text)[:512])[0]
        return result['label']  # returns POSITIVE or NEGATIVE
    except:
        return 'UNKNOWN'

df['Sentiment'] = df['Clean_Text'].apply(get_sentiment)

print("✅ Sentiment analysis done!")
print("\nSentiment distribution:")
print(df['Sentiment'].value_counts())
df[['Text_ID', 'Clean_Text', 'Sentiment']].head(5)

classifier = pipeline("zero-shot-classification",
                      model="facebook/bart-large-mnli")

candidate_labels = [
    "Road Accident",
    "Fire",
    "Theft / Robbery",
    "Assault / Shooting",
    "Public Disturbance",
    "Missing Person",
    "Arrest / Investigation"
]

def classify_topic(text):
    try:
        result = classifier(str(text)[:512], candidate_labels)
        return result['labels'][0]  # top predicted topic
    except:
        return 'Unknown'

df['Topic'] = df['Clean_Text'].apply(classify_topic)

print("✅ Topic classification done!")
print("\nTopic distribution:")
print(df['Topic'].value_counts())
df[['Text_ID', 'Clean_Text', 'Sentiment', 'Topic']].head(5)

# Build the final output dataframe
final_df = pd.DataFrame()

final_df['Text_ID']   = df['Text_ID']
final_df['Source']    = df['Source']
final_df['Raw_Text']  = df['Raw_Text']
final_df['Sentiment'] = df['Sentiment']
final_df['Entities']  = df['Entities']
final_df['Topic']     = df['Topic']

# Save to CSV
final_df.to_csv('/content/text_analyst_output.csv', index=False)

print("✅ Final structured CSV saved!")
print("Shape:", final_df.shape)
print("\nSample output:")
final_df.head(10)

from google.colab import files
files.download('/content/text_analyst_output.csv')

print("=" * 50)
print("TEXT ANALYST PIPELINE — FINAL SUMMARY")
print("=" * 50)
print(f"Total Tweets Processed : {len(final_df)}")
print(f"Sentiment Distribution :\n{final_df['Sentiment'].value_counts()}")
print(f"\nTopic Distribution     :\n{final_df['Topic'].value_counts()}")
print(f"\nOutput File            : text_analyst_output.csv")
print("=" * 50)